// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjlAnHJ78L20Rabe51HIiTWtlzuHnJt4A',
    appId: '1:541107565011:web:3904b41ea1e819c59f3f26',
    messagingSenderId: '541107565011',
    projectId: 'sample-project-591c1',
    authDomain: 'sample-project-591c1.firebaseapp.com',
    storageBucket: 'sample-project-591c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNyCJ9uYZJdJLc0nAC8sxPuburbTEFmOQ',
    appId: '1:541107565011:android:5c94780841cd63ef9f3f26',
    messagingSenderId: '541107565011',
    projectId: 'sample-project-591c1',
    storageBucket: 'sample-project-591c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSdx6g5T69y1NLm4B8hyZLg3GGUFODvvc',
    appId: '1:541107565011:ios:d1c098d0ae8fabd19f3f26',
    messagingSenderId: '541107565011',
    projectId: 'sample-project-591c1',
    storageBucket: 'sample-project-591c1.appspot.com',
    androidClientId: '541107565011-9p1gcsj3fj4hipkdvkb02bot2gvteqt6.apps.googleusercontent.com',
    iosClientId: '541107565011-b3n8vcm8s59q4vlm7c6kt40fhrub20mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.petadpotionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjlAnHJ78L20Rabe51HIiTWtlzuHnJt4A',
    appId: '1:541107565011:web:ec586d987f52ad4f9f3f26',
    messagingSenderId: '541107565011',
    projectId: 'sample-project-591c1',
    authDomain: 'sample-project-591c1.firebaseapp.com',
    storageBucket: 'sample-project-591c1.appspot.com',
  );
}
